//========================BASE DE DATOS========================//
const baseDeDatos = [
    {
      id: 1,
      artist: "Rolling Stones",
      album: "Blue & Lenoseme",
      genre: "rock",
      year: 2016,
      format: "Cd",
      price: 12650,
      img: "../img/Albums/Rolling Stones - Blue & Lenoseme.jpg",
    },
    {
      id: 2,
      artist: "The Beatles",
      album: "Abbey Road",
      genre: "rock",
      year: 2019,
      format: "Vinilo",
      price: 12650,
      img: "../img/Albums/The Beatles - Abbey Road Anniversary.png",
    },
    {
      id: 3,
      artist: "The Killers",
      album: "Pressure Machine",
      genre: "rock",
      year: 2021,
      format: "Cd",
      price: 3000,
      img: "../img/Albums/The Killers - Pressure Machine.jpg",
    },
    {
      id: 4,
      artist: "Cerati",
      album: "Fuerza Natural",
      genre: "nac",
      year: 2009,
      format: "Cd",
      price: 6250,
      img: "../img/Albums/Cerati - Fuerza Natural.jpg",
    },
    {
      id: 5,
      artist: "Ciro y los persas",
      album: "Guerras",
      genre: "nac",
      year: 2020,
      format: "Cd",
      price: 4999,
      img: "../img/Albums/Ciro y los persas - Guerras (Un viaje en el tiempo).jpg",
    },
    {
      id: 6,
      artist: "Divididos",
      album: "Haciendo cosas raras",
      genre: "nac",
      year: 2018,
      format: "Cd",
      price: 3400,
      img: "../img/Albums/Divididos - Haciendo cosas raras.png",
    },
    {
      id: 7,
      artist: "ACDC",
      album: "Live River Plate 2009",
      genre: "hardrock",
      year: 2011,
      format: "CD",
      price: 2360,
      img: "../img/Albums/ACDC -Live in River Plate.jpg",
    },
    {
      id: 8,
      artist: "Metallica",
      album: "S&M2",
      genre: "hardrock",
      year: 2020,
      format: "Cd",
      price: 3077,
      img: "../img/Albums/Metallica - S&M2.png",
    },
    {
      id: 9,
      artist: "Evanescence",
      album: " The Bitter Truth",
      genre: "hardrock",
      year: 2021,
      format: "Cd",
      price: 8750,
      img: "../img/Albums/Evanescence – The Bitter Truth.jpg",
    },
    {
      id: 10,
      artist: "Avicii",
      album: "True",
      genre: "edm",
      year: 2013,
      format: "Cd",
      price: 4310,
      img: "../img/Albums/Avicii - True.jpg",
    },
    {
      id: 11,
      artist: "Marshmello",
      album: " Shockwave",
      genre: "edm",
      year: 2021,
      format: "Cd",
      price: 4550,
      img: "../img/Albums/Marshmello - Shockwave.jpg",
    },
    {
      id: 12,
      artist: "Steve Aoki",
      album: "Neon Future IV",
      genre: "edm",
      year: 2020,
      format: "Cd",
      price: 1600,
      img: "../img/Albums/Steve Aoki - Neon Future IV.jpg",
    },
    {
      id: 13,
      artist: "Drake",
      album: "Certified Lover Boy",
      genre: "hiphop",
      year: 2021,
      format: "Cd",
      price: 2990,
      img: "../img/Albums/Drake - Certified Lover Boy.jpg",
    },
    {
      id: 14,
      artist: "Doja Cat",
      album: "Planet Her",
      genre: "hiphop",
      year: 2021,
      format: "Cd",
      price: 3450,
      img: "../img/Albums/Doja Cat - Planet Her.jpg",
    },
    {
      id: 15,
      artist: "Megan Thee Stallion",
      album: "Good News",
      genre: "hiphop",
      year: 2020,
      format: "Cd",
      price: 3250,
      img: "../img/Albums/Megan Thee Stallion - Good News.jpg",
    },
    {
      id: 16,
      artist: "Maria Becerra",
      album: "Animal",
      genre: "latin",
      year: 2021,
      format: "Cd",
      price: 5400,
      img: "../img/Albums/Maria Becerra - Animal.png",
    },
    {
      id: 17,
      artist: "Bad Bunny",
      album: "El ultimo tour del ...",
      genre: "latin",
      year: 2019,
      format: "Cd",
      price: 3600,
      img: "../img/Albums/Bad Bunny - El ultimo tour del mundo.jpg",
    },
    {
      id: 18,
      artist: "J Balvin",
      album: "Summer Vacation",
      genre: "latin",
      year: 2020,
      format: "Cd",
      price: 4300,
      img: "../img/Albums/J Balvin -  Summer Vacation.jpg",
    },
    {
      id: 19,
      artist: "Dua Lipa",
      album: "Future Nostalgia",
      genre: "pop",
      year: 2020,
      format: "Vinilo",
      price: 12650,
      img: "../img/Albums/Dua Lipa - Future Nostalgia.jpg",
    },
    {
      id: 20,
      artist: "Billie Eilish",
      album: " Happier Than Ever",
      genre: "pop",
      year: 2021,
      format: "Vinilo",
      price: 12650,
      img: "../img/Albums/Billie Eilish - Happier Than Ever.jpg",
    },
    {
      id: 21,
      artist: "Olivia Rodrigo",
      album: "Sour",
      genre: "pop",
      year: 2021,
      format: "Cd",
      price: 4050,
      img: "../img/Albums/Olivia Rodrigo - Sour.jpg",
    },
    {
      id: 22,
      artist: "Blackpink",
      album: "The Album",
      genre: "kpop",
      year: 2020,
      format: "Cd",
      price: 7990,
      img: "../img/Albums/Blackpink - The Album.png",
    },
    {
      id: 23,
      artist: "BTS",
      album: "Butter",
      genre: "kpop",
      year: 2021,
      format: "Cd",
      price: 6990,
      img: "../img/Albums/BTS-Butter.jpg",
    },
    {
      id: 24,
      artist: "TXT",
      album: "The chaos chapter: F or E",
      genre: "kpop",
      year: 2021,
      format: "Cd",
      price: 7990,
      img: "../img/Albums/TXT - The chaos chapter fight or escape.jpg",
    },
  ];

  /* al quitar el comentario del item 25, automaticamente se renderiza dentro de mi lista de productos en el index.html*/

  export default baseDeDatos;